# Basics
site_name: SAST skill docs
repo_url: https://github.com/Ashitemaru/sast-skill-docs
repo_name: SAST skill docs

theme:
  name: material
  language: zh
  custom_dir: theme/
  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
  palette:
    - primary: white
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - def_list
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format

# Contents
nav:
  - 欢迎来到 SAST skill docs:
    - index.md
    - 读者须知: notes/reader.md
    - 编辑者须知: notes/editor.md
  - 课程指引:
    - courses/index.md
  - 基本技能:
    - basic/index.md
    - 如何使用搜索引擎: basic/search-engine.md
    - VSCode 配置: basic/vscode.md
    - Git 入门: basic/git.md
    - Linux 入门: basic/linux.md
    - Markdown 入门: basic/md.md
  - 编程语言:
    - languages/index.md
    - C 语言基础: languages/c-basic.md
    - 现代 C++ 语言: languages/modern-cpp.md
    - Python 语言基础:
      - languages/python/index.md
      - Python 包管理: languages/python/pip.md
      - Python 网络请求与爬虫基础: languages/python/crawler.md
    - HTML 语言基础: languages/html.md
    - CSS 语言基础:
      - languages/css/index.md
      - Bootstrap 简介: languages/css/bootstrap.md
      - MDUI 简介: languages/css/mdui.md
    - JavaScript 语言基础:
      - languages/javascript/index.md
      - JavaScript 的变量与变量类型: languages/javascript/variable.md
      - JavaScript 的控制语句: languages/javascript/control.md
      - JavaScript 的函数: languages/javascript/function.md
      - JavaScript 的面向对象: languages/javascript/oop.md
      - JavaScript 的异步: languages/javascript/async.md
      - JavaScript 的面向对象进阶: languages/javascript/oop-advance.md
      - 浏览器中的 JavaScript: languages/javascript/browser.md
    - TypeScript 语言基础: languages/typescript.md
    - Rust 语言基础: 
      - languages/rust/index.md
      - Rust 入门的一点经验: languages/rust/whyrust.md
      - Rust 的变量与类型: languages/rust/variable.md
      - Rust 中的流程控制: languages/rust/control.md
      - Rust 的函数: languages/rust/function.md
      - Rust 模式匹配: languages/rust/matching.md
      - Rust 的结构体: languages/rust/struct.md
      - Rust 的引用与借用: languages/rust/reference.md
    - Node.js 基础:
      - languages/node.js/index.md
      - npm 简介: languages/node.js/npm.md
    - Swift 语言基础:
      - languages/swift/index.md
      - 基础知识: languages/swift/basic.md
      - 变量和函数: languages/swift/variable-function.md
      - 流程控制: languages/swift/control-flow.md
      - 类型: languages/swift/types.md
      - 泛型: languages/swift/generics.md
      - 部分内置类型: languages/swift/internal-types.md
      - 后续拓展: languages/swift/extensions.md
  - 前端框架:
    - frontend/index.md
    - React 框架入门: frontend/react-easy.md
    - 现代 React 框架: frontend/react-more.md
    - SwiftUI 与 iOS 开发入门:
      - frontend/swiftui/index.md
      - Hello World: frontend/swiftui/hello-world.md
      - 构建 View: frontend/swiftui/build-views.md
      - 数据流基础:  frontend/swiftui/data-flow.md
      - 声明式 UI 与 MVVM: frontend/swiftui/declaritive-mvvm.md
      - 后续拓展: frontend/swiftui/extensions.md
  - 人工智能 & 机器学习:
    - ai-ml/index.md
    - Pytorch 入门: ai-ml/pytorch.md  
    - 对抗搜索: ai-ml/adversarial-search.md
  - 资源链接:
    - source/index.md
    - 书目推荐: source/book.md
    - 外部链接: source/source.md
